---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# The name of the nginx apt/yum package to install.
nginx_package_name: "nginx"

nginx_worker_processes: "1"
nginx_worker_connections: "1024"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "64m"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "dev.web"
    root: "/var/www/dev.web"
    index: "index.php index.html index.htm"
    # error_page: ""
    access_log: "/var/log/nginx/web_access.log"
    error_log: "/var/log/nginx/web_error.log"
    extra_parameters: |
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }

  - listen: "80"
    server_name: "admin.dev.web"
    root: "/var/www/admin.dev.web"
    index: "index.php index.html index.htm"
    # error_page: ""
    access_log: "/var/log/nginx/admin_access.log"
    error_log: "/var/log/nginx/admin_error.log"
    extra_parameters: |
      location / {
        try_files $uri $uri/ /index.php?$args;
      }
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }
