# php7
- name: Add repository remi-repo
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo
- name: install php7
  yum: name={{ item }} enablerepo=remi-php70 state=installed
  with_items:
    - php
    - php-mcrypt
    - php-mbstring
    - php-fpm
    - php-xml
    - php-pdo
- name: Configure php-fpm
  template:
    src: php-fpm-www.conf.j2
    dest: /etc/php-fpm.d/www.conf
- name: start php-fpm
  service: name=php-fpm state=started enabled=yes
